set(CMAKE_SYSTEM_NAME Darwin)

set(OSXCROSS_PATH /opt/osxcross)
set(OSXCROSS_SDK "${OSXCROSS_PATH}/SDK/MacOSX10.11.sdk/")
set(OSXCROSS_PKG_PATH "${OSXCROSS_PATH}/macports/pkgs/opt/local")
set(TOOLCHAIN_PREFIX x86_64-apple-darwin15)

set(CMAKE_C_COMPILER "${OSXCROSS_PATH}/bin/${TOOLCHAIN_PREFIX}-clang")
set(CMAKE_CXX_COMPILER "${OSXCROSS_PATH}/bin/${TOOLCHAIN_PREFIX}-clang++")
set(CMAKE_AR "${OSXCROSS_PATH}/bin/${TOOLCHAIN_PREFIX}-ar")
set(CMAKE_RANLIB "${OSXCROSS_PATH}/bin/${TOOLCHAIN_PREFIX}-ranlib")

set(CMAKE_OSX_SYSROOT ${OSXCROSS_SDK})

set(CMAKE_FIND_ROOT_PATH
	"${OSXCROSS_PATH}"
	"${OSXCROSS_PKG_PATH}")

message("${CMAKE_FIND_ROOT_PATH}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(SDL2_DIR ${OSXCROSS_PKG_PATH}/lib/cmake/SDL2)